In [1]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import seaborn as sns

In [5]:
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv(r"C:\Users\Admin\Downloads\archive (2)\dirty_cafe_sales.csv")

In [7]:
df.head()#first 5 rows

,Transaction ID,Item,Quantity,Price Per Unit,TotalSpent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [8]:
df.tail()#last 5 rows

,Transaction ID,Item,Quantity,Price Per Unit,TotalSpent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2,4,NaN,UNKNOWN,8/30/2023
9996,TXN_9659401,NaN,3,NaN,3,Digital Wallet,NaN,6/2/2023
9997,TXN_5255387,Coffee,4,2,8,Digital Wallet,NaN,3/2/2023
9998,TXN_7695629,Cookie,3,NaN,3,Digital Wallet,NaN,12/2/2023
9999,TXN_6170729,Sandwich,3,4,12,Cash,In-store,11/7/2023

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   TotalSpent        9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [10]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,TotalSpent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3,6,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [11]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
TotalSpent           173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [12]:
df.shape

(10000, 8)

In [13]:
df["Item"] = df["Item"].fillna(df["Item"].mode()[0])

In [14]:
df["Payment Method"] = df["Payment Method"].fillna(df["Payment Method"].mode()[0])